### ISSUE TITLE
update params.ReturnValues to match aws implementation

### ISSUE THREAD

**Issue by michaelwittwer** [shiftcode/dynamo-easy#161]
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html#DDB-UpdateItem-request-ReturnConsumedCapacity

Use ReturnValues if you want to get the item attributes as they appear before or after they are updated. For UpdateItem, the valid values are:

NONE - If ReturnValues is not specified, or if its value is NONE, then nothing is returned. (This setting is the default for ReturnValues.)

ALL_OLD - Returns all of the attributes of the item, as they appeared before the UpdateItem operation.

UPDATED_OLD - Returns only the updated attributes, as they appeared before the UpdateItem operation.

ALL_NEW - Returns all of the attributes of the item, as they appear after the UpdateItem operation.

UPDATED_NEW - Returns only the updated attributes, as they appear after the UpdateItem operation.

**Comment by oreporan** [comment]
Isn't this still an issue regarding the type of `.returnValues()` ?

I see it only accepts:

```ts
    returnValues(returnValues: 'ALL_OLD'): PutRequest<T, T>;
    returnValues(returnValues: 'NONE'): PutRequest<T, void>;
```

**Comment by michaelwittwer** [comment]
@oreporan I see that you are referring to the `returnValues` of a `PutRequest` which is not what this issue was about, the change only affected the update request. Looking at the docs a PutItem request only supports ReturnValues of type.`NONE` and `ALL_OLD`.

https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html#API_PutItem_RequestSyntax
> The ReturnValues parameter is used by several DynamoDB operations; however, PutItem does not recognize any values other than NONE or ALL_OLD.
