### ISSUE TITLE
spread the word

### ISSUE THREAD

**Issue by michaelwittwer** [shiftcode/dynamo-easy#187]
a collection of sources where we can place a link or point to some specific features of dynamo-easy:

**Comment by simonmumenthaler** [comment]
awslabs "Is this project dead?":
https://github.com/awslabs/dynamodb-data-mapper-js/issues/138


asking for promise support:
https://github.com/baseprime/dynamodb/issues/1


project with a similar goal:
https://github.com/kayomarz/dynamodb-data-types


project with fluent api, but outdated:
https://github.com/awspilot/dynamodb-oop


Other project (with deprecated stuff):
https://github.com/dynamoosejs/dynamoose

an issue about combined conditions:
https://github.com/dynamoosejs/dynamoose/issues/542
a feature request about scan on GSI:
https://github.com/dynamoosejs/dynamoose/issues/211
an issue about object/array mapping:
https://github.com/dynamoosejs/dynamoose/issues/445

**Comment by michaelwittwer** [comment]
write to collaborate, seems like they just picked up work again on the library:
https://github.com/trevorhanus/dynaflo/issues
