### ISSUE TITLE
Remove docs from npm package

### ISSUE THREAD

**Issue by OG84** [shiftcode/dynamo-easy#202]
**Is your feature request related to a problem? Please describe.**
I'm using your awesome library in an aws lambda function.
When deploying the function I also have to upload all the node_modules the function requires.
To keep this deployment package as small as possible, it would be nice to get rid of the docs inside the npm package of your library.

**Describe the solution you'd like**
Don't publish docs with the npm package.

**Describe alternatives you've considered**
I can remove it myself before uploading.

**Additional context**
Thanks for the effort you put into this project.

![image](https://user-images.githubusercontent.com/5689965/55672331-1ca08300-589a-11e9-8bab-d56982a334d2.png)

**Comment by michaelwittwer** [comment]
Thanks @OG84 for pointing this out. We never used the library without a bundler, that's why the issue never happened to us. Let us know if you have any other issues.
