### ISSUE TITLE
Map a DynamoDB Stream object to Javascript type

### ISSUE THREAD

**Issue by CasperAlant** [shiftcode/dynamo-easy#205]
Please see my [StackOverflow question](https://stackoverflow.com/questions/55628932/how-to-map-a-dynamodb-streams-object-to-a-javascript-object). After finding a solution with DynamoDB-Data-Mapper, I found out they don't support transactions. I'm trying to do the same thing with Dynamo-easy to no avail.

Please assist. If this is not currently possible in DynamoDB, please consider this a feature request.

**Comment by michaelwittwer** [comment]
Hi @CasperAlant, thanks for reaching out.
This is absolutely possible. Posted an answer to your SO Question. Checkout the docs to learn more about [transactions](https://shiftcode.gitbook.io/dynamo-easy/api/multi-model-requests#transactwrite).

**Comment by clarkd** [comment]
This is awesome - thanks!
