### ISSUE TITLE
Max 5 global secondary indexes per model

### ISSUE THREAD

**Issue by mattia85** [shiftcode/dynamo-easy#206]
Hello,
we are developing our SaaS using this wonderful dynamoDb client and till now everything going well, at this time we have found that you set to 5 the maximum number of GSI per model, why this limit?

According to aws documentation, we can define up to 20 GSI per table, the limit of 5 indexes is for Local Secondary indexes. [GSI limits](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html#limits-secondary-indexes)

We hope the problem will be solved soon.

Thanks

**Comment by mattia85** [comment]
Hello, 
is there any update about this issue?

Thanks

**Comment by michaelwittwer** [comment]
Hi @mattia85. Thanks for pointing this out. Working on it right now, we will remove the limitation due to its variability. It is always possible to request service limit increase depending on requirements. So we think it is not our responsibility to make assumptions. Keep you posted.

**Comment by mattia85** [comment]
Hi @michaelwittwer yes i think so too, this isn't the right place where perform this check because of the variability of the limit.

Thank you.
