### ISSUE TITLE
How to mock calls to DynamoDB

### ISSUE THREAD

**Issue by frak** [shiftcode/dynamo-easy#209]
Where I have the following DynamoStore instance:
```
            const client = new AWS.DynamoDB({apiVersion: '2012-08-10', region: 'eu-west-2'});
            store = new DynamoStore<Event>(Event, client);
```
And the following code to run a query:
```
        const query = await this.store.query();
        query.params.ProjectionExpression = "#pk,#sk";
        const events = await query
            .wherePartitionKey(serviceId)
            .whereSortKey()
            .between(start, end)
            .execFetchAll();
```
I would like to write a test that exercises all of this code to ensure that the correct query is being made to AWS. We typically use the AWSMock library to do this using `AWSMock.setSDKInstance(AWS);`.

My issue is that for some reason, when using dynamo-easy the calls are still made to AWS. I can swap out the above dynamo-easy query with a raw call to Dynamo as follows:
```
        const res = dynamo.query({
            TableName: "test-table",
            ProjectionExpression: "#pk,#sk",
            ExpressionAttributeNames: {"#pk": "pk", "#sk": "sk"},
            ExpressionAttributeValues: {
                ":pk": {S: "4164"},
                ":sk": {S: "1554940800000"},
                ":sk_2": {S: "1555027199000"},
            },
            KeyConditionExpression: "#pk = :pk AND #sk BETWEEN :sk AND :sk_2"
        }).promise();
```
And the AWSMock library intercepts the call as expected. Can you please assist in what I am missing to make this work?

**Comment by frak** [comment]
Of course, I find my own solution minutes after creating an issue here :(

My code was setting the mock expectation after I instantiated the DynamoStore class. By moving the mock expectations to before where DynamoStore is instatiated things started working as expected.

**Comment by michaelwittwer** [comment]
@frak good to hear it works for you
