### ISSUE TITLE
Multi database configuration

### ISSUE THREAD

**Issue by vkartaviy** [shiftcode/dynamo-easy#210]
For now due to a global `dynamoEasyConfig` object it's not possible to create separate table name resolvers for different database connections.

**Comment by michaellieberherr** [comment]
@vkartaviy Could you elaborate a bit on your use case, maybe there is an other solution.

**Comment by vkartaviy** [comment]
@michaellieberherr I need to use dynamodb tables from different AWS accounts and one of them has table name prefix based on stage and another one not. 

For now I overcame this by adding "namespace" to the models `tableName` property `@Model({ tableName: 'db1:Users' })` and `@Model({ tableName: 'db2:Devices' })` and inside `tableNameResolver` I remove/replace this "namespace" with prefix. 

So issue can be closed but I think having global object is not so good from library design perspectives.

**Comment by michaelwittwer** [comment]
@vkartaviy thanks for the insights. I see your point and can imagine we might change this in the future if more people request this. Happy to see you found a nice workaround.
