### ISSUE TITLE
@Property custom name doesn't work with @PartitionKey together

### ISSUE THREAD

**Issue by vkartaviy** [shiftcode/dynamo-easy#215]
**Describe the bug**
When I am trying to set custom name for `@PartitionKey` it doesn't applied in requests. 
```
@PartitionKey()
@Property({ name: 'custom_id' })
id: string;
```

**Expected behavior**
I expect that `id` became `custom_id` in requests to match the database schema and also correctly mapped to the model property from responses.
Request: id -> custom_id
Response: custom_id -> id

**Comment by michaelwittwer** [comment]
Hi @vkartaviy. I was not able to reproduce the issue. Could you provide a repro? Here is the one I created to verify https://stackblitz.com/edit/dynamo-easy-multiple-decorators. I know this are not real life circumstances using the fromDb function and maybe you did also not use a put request to write, please provide some more details.

**Comment by vkartaviy** [comment]
Try to test with `get` request
```
const getRequest = store.get('idValue')
console.log(getRequest.params.Key);
```
and you will get 
```
{
  "id": {
    "S": "idValue"
  }
}
```
but should get `custom_id` instead.

**Comment by michaelwittwer** [comment]
@vkartaviy identified the issue. Thanks for pointing this out.
