### ISSUE TITLE
Error on scan when there's a 'Where' with an 'or' inside - Invalid FilterExpression: The expression has redundant parentheses;

### ISSUE THREAD

**Issue by Rodolfobm** [shiftcode/dynamo-easy#216]
**Describe the bug**
I wanted to filter a `scan ` using 2 attributes, so I'm using an `Or` expression with 2 `attribute('attribute').beginsWith(var)` inside. 

When I run the code under 'steps to reproduce', I get a **Invalid FilterExpression: The expression has redundant parentheses;** from CloudWatch logs.

When I print `query.params`, being `query` my `ScanRequest` I get the following object:

```
{ 
    TableName: 'My_Dynamo_Table',
    Limit: 10,
    ExpressionAttributeNames: { '#fullName': 'fullName', '#country': 'country' },
    ExpressionAttributeValues: { ':fullName': { S: 'gua' }, ':country': { S: 'gua' } },
    FilterExpression: '((begins_with (#fullName, :fullName) OR begins_with (#country, :country)))'
}
```

**Note the extra parentheses at `Filter Expression`**

**OBS:** If only 1 condition is passed using `whereAttribute('attribute').beginsWith(var)` it works just fine.

**To Reproduce**
 
Just try to scan a table with 2 or more conditions inside an `or` operation:

```
public async find(startKey?: string, filter?: string): Promise<[Entity[], DynamoDB.Key]> {

        const scanRequest= this.store.scan().limit(10);

        if (startKey) { query.exclusiveStartKey(JSON.parse(startKey)); }

        if (filter) {
            scanRequest.where(or(
                attribute('fullName').beginsWith(filter),
                attribute('country').beginsWith(filter)
            ));
        }
        const response = await scanRequest.execFullResponse();
        return [response.Items, response.LastEvaluatedKey];
}
```

**Expected behavior**

Expected to filter scan results by both conditions.

**Desktop (please complete the following information):**
 - Nodejs 8.10
 - AWS' Lambda Environment.

**Additional context**
This is my first time working with dynamo and dynamo-easy, so this may be an error of mine.

**Comment by Rodolfobm** [comment]
The workaround I found, in case someone else is with the same problem is to apply a `slice(1, -1)` at `scanReq.params.FilterExpression` so it removes the initial and final parentheses of the filter.

**Comment by michaellieberherr** [comment]
@simonmumenthaler : could you have a look
