### ISSUE TITLE
Query by array of partition keys using new BatchGetRequest().forModel() causes error

### ISSUE THREAD

**Issue by craigcartmell** [shiftcode/dynamo-easy#219]
**Describe the bug**
When making a batch get request for a model passing an array of partition keys, I receive the following error:

`sk is null but is a RANGE key`

DynamoDB seems to allow batch get requests solely on a partition key by omitting the sort key from the request altogether (unless I'm misunderstanding...).

**To Reproduce**

1. Create example model and table:

```
@Model({ tableName: "some-name" })
export class MyModel {
    @PartitionKey()
    public pk: string;

    @SortKey()
    @Property()
    public sk: string;
}
```

2. Attempt to execute the following query:

```
      await new BatchGetRequest().forModel(
            MyModel,
            [{pk: "pk-1"}, {pk: "pk-2"}],
        ).exec();
```

3. See `sk is null but is a RANGE key` error

**Expected behavior**
I expect the query to be executed successfully.

**Context**
The error is thrown in `dist/mapper/mapper.js` line 102`.

**Comment by michaellieberherr** [comment]
Thanks for reporting the issue. According to the AWS documentation it's not possible to batchGet only by the Partition Key if a Range Key is present: https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchGetItem.html

>Keys - An array of primary key attribute values that define specific items in the table. For each primary key, you must provide all of the key attributes. For example, with a simple primary key, you only need to provide the partition key value. For a composite key, you must provide both the partition key value and the sort key value.

Feel free to correct me if I'am wrong. Closing for the moment.

**Comment by craigcartmell** [comment]
Thanks for the quick response @michaellieberherr. 

On that note, any idea how the DynamoDB console works as it executes successfully with just the  PK and leaving the SK blank? See [screenshot](https://imgur.com/a/mXRgAEz).

**Comment by craigcartmell** [comment]
Secondary to that, what do you think is the most efficient way of using Dynamo Easy to fetch multiple records based on an array of partition keys?

**Comment by michaellieberherr** [comment]
@craigcartmell You can use a Query for getting all items based only on the PartitionKey (only as single partition key) without specifying a SortKey
(see https://shiftcode.gitbook.io/dynamo-easy/api/dynamo-store/model-requests#query) if you need to access multiple items with different partition keys you have to do a separate Query per PK (as the PK is a **PARTITION** Key and is internally used for partitioning the items, usually you can circumvent a lot of issues by changing your data models, but that's not always that obvious ). I recommend you to read the Best practices guide by AWS: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/best-practices.html
