### ISSUE TITLE
Query doesn't return the right object type

### ISSUE THREAD

**Issue by mattia85** [shiftcode/dynamo-easy#220]
Hello,
i have a problem with the instance returned by the query operation (also with get op):

```
const store: DynamoStore<OrderModel> = new DynamoStore<OrderModel>(OrderModel);
const getOrder = await store
   .query()
   .index(indexName)
   .wherePartitionKey(order.storeOrderId)
   .whereSortKey().eq(order.selectedStoreId)
   .execSingle();
```
my expectation was that the type of the object returned from the above query should be the one declared during the store definition, but i'm getting a simply js Object instead of an OrderModel, any idea?

Thank you.

**Comment by michaelwittwer** [comment]
Hi @mattia85 
This is how the library is supposed to work, we don't create instances of the provided model class. So an `instanceof` check will always return `false`.  The model class is only defined for metadata purposes, any business logic should be provided in pure helper methods.

**Comment by mattia85** [comment]
ok @michaellieberherr, thanks for clarifying that.
