### ISSUE TITLE
Strongly consistent reads option for query and scan requests

### ISSUE THREAD

**Issue by hoonoh** [shiftcode/dynamo-easy#230]
It would be great to have strongly consistent read options for query and scan operations like like how it is supported by get operation `get().onsistentRead()`.

**Comment by simonmumenthaler** [comment]
hi @hoonoh 
Thanks for opening the issue. We'll cover this in the near future.

In the meantime you can use consistent read by extending the params. 
> Every request instance contains the public params property where all params for the request are written to.

```
const queryRequest =  new DynamoStore(YourModel).query()
  .wherePartitionKey('2018-01')
  .whereSortKey().beginsWith('a')

queryRequest.params.ConsistentRead=true

queryRequest.execSingle().then(v => {})
```
