### ISSUE TITLE
model metadata: improve properties/index handling

### ISSUE THREAD

**Issue by simonmumenthaler** [shiftcode/dynamo-easy#250]
- [ ] metadata model "properties" and "indexes" are optional --> always provide a value. (-->  usage can be simplified when doing so)
- [ ] some more tests for mapper & decorator

**Comment by hookercookerman** [comment]
@simonmumenthaler was going to raise an issue that you cannot specify a type of `string | undefined` for a GSI property decorator (this results in a error not sure at the mo, but modelOptions will be undefined and when calling toDb subsequent calls will end up calling `properties` on the undefined modelOptions. But from your `indexes` are optional quote above this may already be known ?? cheers

**Comment by simonmumenthaler** [comment]
I don't think it's directly related to the PR.
I couldn't reproduce your case - but I realized that for Reflect it differs wether you use `gsi: string|undefined` or `gsi?: string`.
Reflect can't get the `string` type when using the first option; which might causes the problem.

**Comment by hookercookerman** [comment]
@simonmumenthaler thanks for reply; its fine now so thanks no probs
