### ISSUE TITLE
Question: Update attribute based on other attribute

### ISSUE THREAD

**Issue by chrisbrantley** [shiftcode/dynamo-easy#255]
I am trying to encapsulate some logic related to updates. For example, if someone updates attribute X I would like to automatically update attribute Y. This is to handle some typical DynamoDB best practices like creating a composite key based on the values of multiple attributes.

What I would LIKE would be a way to hook in to the update mechanism and add my own update expressions based on the values of other update expressions. I could inspect the updates and see that attribute X is being set to a new value so then I could set attribute Y to another appropriate value.

A alternative to this is simply to handle this logic in a higher level of abstraction and I'm prepared to do that, however I have been impressed with the level of abstraction I'm getting with dynamo-easy and would love to handle this logic by extending my Model or DynamoStore classes.

Thank you in advance for your consideration and guidance.

**Comment by simonmumenthaler** [comment]
Hi @chrisbrantley 

When updating a property, we do not have the whole object and are therefore not able to access other property values to update a composite key **than** the `key` and the updated value.
```
personStore.update('my-id').updateAttribute('name').set('simon').exec()
``` 
(eg. a composite key with `${birthday}-${name}` --> where to get birthday from?)

We handle composite keys by using an own type and a custom mapper. This way you're forced to always provide all necessary values. An example can be found in our running demo:
* [Model with Composite Key](https://stackblitz.com/edit/dynamo-easy-node-sample?file=model%2Ftime-entry.model.ts)
* [Type/Class of Composite Key](https://stackblitz.com/edit/dynamo-easy-node-sample?file=model%2Fmonth-email.model.ts)
* [Mapper for Composite Key](https://stackblitz.com/edit/dynamo-easy-node-sample?file=model%2Fmonth-email.mapper.ts)
