### ISSUE TITLE
Question: DynamoDB endpoint config

### ISSUE THREAD

**Issue by d-w4lsh** [shiftcode/dynamo-easy#256]
Is there anyway to configure dynamo-easy to use a predefined endpoint? I use a local in-memory DynamoDB instance for my unit tests and I would your library to point to it.

**Comment by michaellieberherr** [comment]
There was an other issue concerning your questions - see: https://github.com/shiftcode/dynamo-easy/issues/237
Closing for the moment - feel free to reopen if you're not satisfied.
