### ISSUE TITLE
Missing tslib dependency

### ISSUE THREAD

**Issue by Tirke** [shiftcode/dynamo-easy#258]
**Describe the bug**
tslib is required to run dynamo-easy in node. tslib is not declared anywhere in the dependencies.

**To Reproduce**
Just run dynamo-easy in node without ts-lib, and it will crash.

**Expected behavior**
ts-lib should be an explicit dependency (peer or not)

**Desktop (please complete the following information):**
 - OS: macOs
 - Version latest of everything

**Comment by michaelwittwer** [comment]
Thanks @Tirke for reporting this. You are absolutely right about this, will change this in the near future.

**Comment by ali-habibzadeh** [comment]
I still get this error on version `5.6.0`
