### ISSUE TITLE
Issue when trying to update a map element where the key constains a dot

### ISSUE THREAD

**Issue by LeandroDG** [shiftcode/dynamo-easy#259]
When trying to update an element using the operations update, I can't find a way to update a map attribute where the name constains a dot.

Sample json: 
```
{
   "myMap": {
       "myNormalChild": "a",
       "myChild.hasADot": "a"
   }
}
```

Update code:
```
    const operations: UpdateExpressionDefinitionFunction[] = [];
    operations.push(update("myMap.myNormalChild").set("sample"));
    operations.push(update("myMap.myChild.hasADot").set("sample"));

    const updateOp = this.hotelStore.update(hotelId);
    await updateOp.operations(...operations).exec();
```

This will correctly update the child "myNormalChild" but will not update "myChild.hasADot". I can't find a way to specify that a map attribute name contains a dot, it will always try to navigate the hierarchy and set the value to myMap => myChild => hasADot. I tried specifying the attribute name within double quotes, or using an array format myChild["hasADot"] but none of those worked.

Thanks!

**Comment by LeandroDG** [comment]
Hi @michaelwittwer, is there a way to work with a map property with a dot and I haven't seen it or is this something we can work on?

Thanks,
Leandro

**Comment by simonmumenthaler** [comment]
I think it is very bad practice to have a dot in a name.

The only way I can think of is using a placeholder name and then changing the value of this placeholder in `request.params.ExpressionAttributeNames`.

```
const request = new UpdateRequest(<any>null, ModelX, 'myId')
      .operations(update('myMap.PLACEHOLDER').set('sample'))
      request.params.ExpressionAttributeNames['#PLACEHOLDER'] = 'myChild.hasADot'
```


-> since we won't do anything about this, I'm closing this issue.

**Comment by LeandroDG** [comment]
Sometimes it's just about being able to handle json structures we haven't
designed. That's the reason for this requirement.

If I do a pull request including support for this will you accept it?

Thanks
Leandro
