### ISSUE TITLE
Documentation: .index must be called before .wherePartitionKey

### ISSUE THREAD

**Issue by jthomerson** [shiftcode/dynamo-easy#301]
It would be good to show examples of querying on a GSI in the documentation. I was scratching my head for a while because I had code like this:

```ts
async function find(pk: string, skPrefix?: string, index?: MyIndexEnum): Promise<Foo[]> {
   let query = store.query().wherePartitionKey(pk);

   if (index) {
      query = query.index(index);
   }

   if (skPrefix && !isEmpty(skPrefix)) {
      query = query.whereSortKey().beginsWith(skPrefix.toLowerCase());
   }

   console.debug(`Query ${index || 'table'} for "${pk}" begins_with(${skPrefix})`);

   return query.exec();
}
```

I didn't realize that you had to call `.index(...)` _before_ calling `wherePartitionKey`. That seems a bit counterintuitive on this builder pattern, but if it was documented [along with the query documentation](https://shiftcode.gitbook.io/dynamo-easy/api/dynamo-store/model-requests#query), that'd make it easy to see.

**Comment by michaelwittwer** [comment]
@jthomerson also closing in favour of #374, thanks for bringing that to our attention
