### ISSUE TITLE
Documentation: How to increase the logging level

### ISSUE THREAD

**Issue by jthomerson** [shiftcode/dynamo-easy#302]
I can't find any documentation on how to increase the logging level. That'd be very helpful to have documented so that when you run into an issue (like I did in #301), you can more easily debug it. I resulted to a hack like this after poking around in the code and old pull requests for a while. I'm sure there's a much easier way - probably with some env var.

```
import { updateDynamoEasyConfig } from '@shiftcoders/dynamo-easy';

updateDynamoEasyConfig({
   logReceiver: console.log,
});
```

**Comment by jthomerson** [comment]
I hope you don't mind me raising these issues. I'm just trying to make note of things that tripped me up as a fairly new user of this package. If I have time later, I'll come back and submit some PR's, but for right now I'm just trying to make sure I don't forget the roadblocks I hit during initial adoption.

**Comment by michaelwittwer** [comment]
@jthomerson sorry for the late reply. Love that you are submitting your learning path, so others can profit from that. Closing this in favour of #374 holding relevant topics to be updated in the docs, serving as a knowledge base for now or pinning missing topics and also describing the strategy of the technical solution of the documentation part, envision it to be closer to the source code of the project
