### ISSUE TITLE
How CollectionProperty works for CustomType?

### ISSUE THREAD

**Issue by scon-io** [shiftcode/dynamo-easy#304]
The docs says that when I use `@CollectionProperty({ itemType: CustomType* })`, `CustomType` must be `@Model` decorated. If I define like the below, what format is a `A` record stored as?

```ts
@Model()
class A {
  ...
  @CollectionProperty({ itemType: B })
  bs: B[];
}

@Model()
class B {
  @PartitionKey()
  pk: string;

  @SortKey()
  sk: string;
}
```

**Comment by simonmumenthaler** [comment]
Your `PartitionKey`/`SortKey ` decorators in class B are useless in this example since it is nested in `A`.

When storing an `A` item the `bs` property will be mapped to a (L)ist attribute containing (M)ap attributes.

**Comment by scon-io** [comment]
@simonmumenthaler 
you mean that `B` is not related with any table even if it is `@model` decorated.

Thank you :)
