### ISSUE TITLE
How to have default values for properties? [Question]

### ISSUE THREAD

**Issue by ali-habibzadeh** [shiftcode/dynamo-easy#306]
Let's assume in the model below i don't want to have to set ttl everytime I do a put operation, so I want this set automatically always by default. I did try to make it optional and set it on the mode like below, but that doesn't actually write it to the db.

Is there a current workaround for this? 

```typescript
@Model({ tableName: appConfig.urlsTableName })
export class CrawlUrl {
  @PartitionKey()
  public url!: string;
  public level: number = 0; // <--- This won't be used
  private ttl? = moment().add(1, "days").unix().toString(); // <--- This won't be used
}
```

**Comment by ali-habibzadeh** [comment]
Does the model ever get newed? That might allow for using default values but at the moment, they simply get ignored.

**Comment by davehensley** [comment]
I think you would need to use a constructor:
```
  constructor(props: { level?: number; ttl?: string }) {
    this.level = props.level || 0;
    this.ttl = props.ttl || moment().add(1, "days").unix().toString();
  }
```

**Comment by davehensley** [comment]
Update: there seems to be a new `defaultValueProvider` feature that was just added: https://github.com/shiftcode/dynamo-easy/issues/244

**Comment by michaelwittwer** [comment]
@ali-habibzadeh I hope that the PR #268 solves your issue, closing this for now.
