### ISSUE TITLE
[Question] Is it possible to define the table name at run time?

### ISSUE THREAD

**Issue by mariobittencourt** [shiftcode/dynamo-easy#307]
Hi, I would like to be able to define the table name at run time. Right now, at least from what I gathered I can only specify the table name with the @Model config options , which seems to be defined only at the definition of the model itself.

Regards,

**Comment by simonmumenthaler** [comment]
```
updateDynamoEasyConfig({  
  tableNameResolver: (tableName: string) =>  `myPrefix-${tableName}`
 })
```

Please have a look here:
https://shiftcode.gitbook.io/dynamo-easy/api/dynamo-easy-config/configuration#tablenameresolver

**Comment by mariobittencourt** [comment]
thank you @simonmumenthaler
