### ISSUE TITLE
How to delete all the rows from a table?

### ISSUE THREAD

**Issue by itsdarrylnorris** [shiftcode/dynamo-easy#321]
How can I wipe an entire table with a single command? Using BatchWrite?

**Comment by akleiber** [comment]
you can't - the easiest and cheapest way to do this is to delete the whole table and create a new one.

**Comment by akleiber** [comment]
if you want to do this without table deletion you have to scan the table and delete the records that are returned

**Comment by itsdarrylnorris** [comment]
Thanks @akleiber , I ended up adding an expiring time to each row, and use the update command to either add/update, and a combination of both of these things fixed my problem.

Closing this ticket.
