### ISSUE TITLE
`update` has "upsert" functionality

### ISSUE THREAD

**Issue by felipevyg** [shiftcode/dynamo-easy#360]
**Is your feature request related to a problem? Please describe.**
The update method has actually upsert functionality, where it will create the item if it not exists. This took me a while to realise since it's not documented.

**Describe the solution you'd like**
Docs be updated with the actual behaviour.

**Comment by michaelwittwer** [comment]
closing this in favour of #374 holding relevant topics to be updated in the docs, serving as a knowledge base for now and also describing the strategy of the technical solution of the documentation part, envision it to be closer to the source code of the project
