### ISSUE TITLE
question: how to write unit tests

### ISSUE THREAD

**Issue by hassanazharkhan** [shiftcode/dynamo-easy#364]
Is there any guide that state how to write unit tests using jest or any other lib?

if not, it would be worth while to have some docs / guide on writing unit tests using jest or any other common lib.

**Comment by michaelwittwer** [comment]
@hassanazharkhan why do you think there should be a guide on how to write unit tests? Are currently blocked on  a potential PR because you can't write the test or what's the purpose of this issue?

I don't think there is any special implementation in the tests, plain jest basically.
