### ISSUE TITLE
Is this repo not maintained anymore? (need support for @aws-sdk/*)

### ISSUE THREAD

**Issue by ali-habibzadeh** [shiftcode/dynamo-easy#408]
I love this library but it seems the maintenance is no longer happening? The lib stopped working with the new version of the SDK.

Currently with the new version you get `Error: Cannot find module 'aws-sdk/clients/dynamodb'` since the new SDK is in `@aws-sdk/client-dynamodb`

**Comment by michaelwittwer** [comment]
related to #286
