### ISSUE TITLE
Increase `BATCH_WRITE_MAX_REQUEST_ITEM_COUNT` from 25 to 100

### ISSUE THREAD

**Issue by amit-alkobi-env0** [shiftcode/dynamo-easy#421]
**Describe the bug**
BATCH_WRITE_MAX_REQUEST_ITEM_COUNT is currently 25, but [AWS increased](https://aws.amazon.com/about-aws/whats-new/2022/09/amazon-dynamodb-supports-100-actions-per-transaction/) it to 100

**To Reproduce**
-

**Expected behavior**
BATCH_WRITE_MAX_REQUEST_ITEM_COUNT = 100

**Desktop (please complete the following information):**
-

**Smartphone (please complete the following information):**
-

**Additional context**
-

**Comment by michaelwittwer** [comment]
Hi @amit-alkobi-env0.
Thanks for reaching out. Why did you close the issue, is it not relevant? Happy to accept PR for this improvement.
