### ISSUE TITLE
node & angular showcase project

### ISSUE THREAD

**Issue by michaelwittwer** [shiftcode/dynamo-easy#49]
- [x] node showcase project using glitch
- [x]  ~~angular showcase project using stackblitz (also use pagedLoader to display data)~~

**Comment by michaelwittwer** [comment]
we are not gonna implement the angular showcase for now

**Comment by damianesteban** [comment]
I would love to see a node.js project taking full advantage of this client - it is quote impressive.

**Comment by michaelwittwer** [comment]
@damianesteban we are in the process of finishing our next big release which will include a node sample showing a whole bunch of different use cases, make sure to start using the library with the beta release (npm beta dist-tag), which will soon be merged to the master, and changes a lot. Watch this issue to get updates.

**Comment by michaelwittwer** [comment]
@damianesteban we published a node sample on stackblitz, check it out https://stackblitz.com/edit/dynamo-easy-node-sample
